describe('template spec', () => {
  it('passes', () => {
    cy.visit('http://localhost:3000/')
    cy.get("#password").type("pfnassar1")
    cy.get("#email").type("pfnassar@calpoly.edu")
    cy.contains("Log in").click()
    cy.contains("Daily Calories", { timeout: 10000 }).should('be.visible')
    cy.contains("3").click()
    cy.wait(1000)
    cy.contains("5").click()
    cy.contains("Profile").click()
    cy.contains("Personal Info").click()
    cy.get("a[href=\"/\"]").click()
    cy.get("button[id=\"radix-:r5:\"]").click()
    cy.contains("Light").click()
    cy.wait(1000)
    cy.get("button[id=\"radix-:r5:\"]").click()
    cy.contains("Dark").click()
    cy.contains("Record Meals").click()
    cy.get("button[data-sidebar=\"trigger\"]").click()
    cy.get("input[placeholder=\"Search for a food\"]").type("eggs{enter}")
    cy.get("input[placeholder=\"Filter food...\"]").type("fried{enter}")
    cy.get("button[aria-label=\"Select all\"]").click()
    cy.contains("Clear").click()
    cy.get("input[placeholder=\"Search for a food\"]").type("{backspace}{backspace}{backspace}{backspace}fruit{enter}")
    cy.get("input[placeholder=\"Filter food...\"]").type("{backspace}{backspace}{backspace}{backspace}{backspace}{backspace}{enter}")
    cy.contains("Fruit Salad").parents('tr').find('button[aria-label=\"Select row\"]').click()
    cy.contains("Submit").click()
    cy.get("button[data-sidebar=\"trigger\"]").click()
    cy.contains("Home").click()
  })
})